import type { EvaluationStatus } from '@/api/schemas';
import type { ReactNode } from 'react';
import { Button } from '@cloudflare/kumo/components/button';
import { DownloadSimple, Flask, Stop } from '@phosphor-icons/react';
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { getSilhouetteChartBounds } from './silhouetteChart';

const labels: Record<string, string> = { time_only_fixed: 'Time-only fixed', contextual_fixed: 'Contextual fixed', contextual_adaptive: 'Contextual adaptive' };

export function PostReplayEvaluation({ replayStatus, evaluation, onStart, onCancel, onDownload }: { replayStatus?: string; evaluation?: EvaluationStatus; onStart: () => void; onCancel: () => void; onDownload: () => void }) {
  const running = evaluation?.status === 'RUNNING';
  const eligible = replayStatus === 'COMPLETED' || replayStatus === 'STOPPED';
  const silhouette = evaluation?.results.structural_silhouette;
  const sensitivity = (evaluation?.results.sensitivity ?? []) as Array<Record<string, unknown>>;
  const noise = (evaluation?.results.noise_robustness ?? []) as Array<Record<string, unknown>>;
  const sensitivityRows = sensitivity.map((row) => ({ delta_t_min: Number(row.delta_t_min), n_meta: Number(row.n_meta), arr: Number(row.arr), execution_time_ms: Number(row.execution_time_ms) }));
  const methods = ['time_only_fixed', 'contextual_fixed', 'contextual_adaptive'];
  const noiseRows = Array.from(new Set(noise.map((row) => Number(row.noise_rate) * 100))).sort((a, b) => a - b).map((rate) => {
    const grouped = noise.filter((row) => Number(row.noise_rate) * 100 === rate);
    return methods.reduce<Record<string, number | string | null>>((point, method) => { const row = grouped.find((item) => String(item.variant) === method); point[method] = row && rate > 0 ? Number(row.noise_absorption_rate) : null; point[`${method}_degradation`] = row ? Number(row.arr_degradation) : null; return point; }, { noise_rate: rate });
  });
  const nullHistogram = silhouette?.null_histogram ? silhouette.null_histogram.counts.map((count, index) => ({ x: (silhouette.null_histogram!.bin_edges[index] + silhouette.null_histogram!.bin_edges[index + 1]) / 2, width: silhouette.null_histogram!.bin_edges[index + 1] - silhouette.null_histogram!.bin_edges[index], count })) : [];
  const silhouetteBounds = nullHistogram.length > 0
    ? getSilhouetteChartBounds(nullHistogram, silhouette?.observed_silhouette, silhouette?.random_mean)
    : null;
  return (
    <section className="rounded-2xl border border-kumo-hairline bg-kumo-canvas p-6 shadow-xs" aria-labelledby="post-eval-title">
      <div className="flex flex-wrap items-start justify-between gap-4"><div><h2 id="post-eval-title" className="text-lg font-bold text-kumo-strong">Evaluasi lengkap RBTA & Isolation Forest</h2><p className="mt-1 max-w-3xl text-sm text-kumo-subtle">Dijalankan setelah replay: sensitivitas Δt, tiga ablation, lima tingkat noise, runtime 5×, frozen-model scoring, dan Silhouette 100 permutasi.</p></div><div className="flex gap-2">{running ? <Button size="sm" variant="outline" onClick={onCancel}><Stop size={14} className="mr-1" />Batalkan</Button> : <Button size="sm" variant="primary" disabled={!eligible} onClick={onStart}><Flask size={14} className="mr-1" />Jalankan evaluasi</Button>}{evaluation?.artifact_available && <Button size="sm" variant="outline" onClick={onDownload}><DownloadSimple size={14} className="mr-1" />Unduh artifact</Button>}</div></div>
      <div className="mt-5"><div className="mb-2 flex justify-between text-xs"><span className="font-semibold text-kumo-default">{evaluation?.current_phase?.replace(/_/g, ' ') || 'menunggu replay selesai'}</span><span className="font-mono text-kumo-subtle">{evaluation?.progress_percent ?? 0}%</span></div><div className="h-2 overflow-hidden rounded-full bg-kumo-recessed"><div className="h-full rounded-full bg-emerald-500 transition-all" style={{ width: `${evaluation?.progress_percent ?? 0}%` }} /></div></div>
      {evaluation?.last_error && <p className="mt-4 rounded-lg bg-red-500/10 p-3 text-xs text-red-700 dark:text-red-300">{String(evaluation.last_error.message ?? 'Evaluasi gagal')}</p>}
      {evaluation && evaluation.completed_phases > 0 && <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        <div className="rounded-xl bg-kumo-recessed/50 p-3"><div className="text-[10px] font-semibold uppercase text-kumo-subtle">Sensitivitas Δt</div><div className="mt-1 text-sm font-bold text-kumo-strong">{evaluation.results.sensitivity?.length ?? 0} skenario</div><div className="text-xs text-kumo-subtle">Elbow: {evaluation.results.recommended_elbow_delta_t_minutes ?? '—'} menit</div></div>
        <div className="rounded-xl bg-kumo-recessed/50 p-3"><div className="text-[10px] font-semibold uppercase text-kumo-subtle">Noise robustness</div><div className="mt-1 text-sm font-bold text-kumo-strong">{evaluation.results.noise_robustness?.length ?? 0} kombinasi</div><div className="text-xs text-kumo-subtle">5 rate × 3 agregasi</div></div>
        <div className="rounded-xl bg-kumo-recessed/50 p-3"><div className="text-[10px] font-semibold uppercase text-kumo-subtle">Runtime</div><div className="mt-1 text-sm font-bold text-kumo-strong">{evaluation.results.runtime?.repetitions ?? 0}× per subset</div><div className="text-xs text-kumo-subtle">R² {evaluation.results.runtime ? evaluation.results.runtime.r_squared.toFixed(4) : '—'} · median/IQR</div></div>
        <div className="rounded-xl bg-kumo-recessed/50 p-3"><div className="text-[10px] font-semibold uppercase text-kumo-subtle">Frozen IF</div><div className="mt-1 text-sm font-bold text-kumo-strong">{evaluation.results.isolation_forest?.meta_alert_count ?? 0} meta-alert</div><div className="text-xs text-kumo-subtle">Refit: {evaluation.results.isolation_forest?.refit_performed ? 'ya' : 'tidak'}</div></div>
      </div>}
      {evaluation?.results.aggregation_ablation && <div className="mt-6 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b border-kumo-hairline text-kumo-subtle"><th className="py-2">Skenario</th><th>Meta-alert</th><th>ARR</th><th>Context purity</th><th>Kontaminasi</th></tr></thead><tbody>{evaluation.results.aggregation_ablation.map(row => <tr key={row.variant} className="border-b border-kumo-hairline/50"><td className="py-3 font-semibold text-kumo-strong">{labels[row.variant] ?? row.variant}</td><td>{row.n_meta}</td><td>{row.arr.toFixed(2)}%</td><td>{row.context_purity_percent.toFixed(2)}%</td><td>{row.context_contamination_percent.toFixed(2)}%</td></tr>)}</tbody></table></div>}
      {sensitivityRows.length > 0 && <div className="mt-6 grid gap-5 lg:grid-cols-2"><ChartCard title="Sensitivitas Δt — jumlah MetaAlert" question="Bagaimana ukuran agregat berubah ketika Δt diubah?" data={sensitivityRows}><Line dataKey="n_meta" stroke="#0055dc" name="MetaAlert" /></ChartCard><ChartCard title="Sensitivitas Δt — ARR" question="Berapa pengurangan unit triase untuk tiap Δt?" data={sensitivityRows}><Line dataKey="arr" stroke="#f6821f" name="ARR (%)" /></ChartCard></div>}
      {noiseRows.length > 0 && <div className="mt-6 grid gap-5 lg:grid-cols-2"><ChartCard title="Dampak noise sintetis terhadap ARR" question="Sumbu X: proporsi noise benign sintetis yang diinjeksi (%). Sumbu Y: penurunan ARR terhadap baseline (poin persentase)." data={noiseRows} xKey="noise_rate"><Line dataKey="time_only_fixed_degradation" stroke="#6b7280" name="Time-only fixed" /><Line dataKey="contextual_fixed_degradation" stroke="#f6821f" name="Contextual fixed" /><Line dataKey="contextual_adaptive_degradation" stroke="#0055dc" name="Contextual adaptive" /></ChartCard><ChartCard title="Alert noise yang terserap ke MetaAlert" question="Sumbu X: proporsi noise benign sintetis yang diinjeksi (%). Sumbu Y: noise absorption rate (%). Nilai 0% adalah N/A." data={noiseRows} xKey="noise_rate"><Line dataKey="time_only_fixed" stroke="#6b7280" name="Time-only fixed" connectNulls={false} /><Line dataKey="contextual_fixed" stroke="#f6821f" name="Contextual fixed" connectNulls={false} /><Line dataKey="contextual_adaptive" stroke="#0055dc" name="Contextual adaptive" connectNulls={false} /></ChartCard></div>}
      {nullHistogram.length > 0 && silhouetteBounds && <div className="mt-6 rounded-xl border border-kumo-hairline p-4"><h3 className="text-sm font-semibold text-kumo-strong">Distribusi null permutation Silhouette</h3><p className="mt-1 text-xs text-kumo-subtle">Silhouette menilai pemisahan struktural internal. Histogram 100 label permutation acak; garis tegas = observed Silhouette, garis putus-putus = rata-rata null. Ini bukan akurasi atau kebenaran serangan.</p><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-kumo-subtle"><span><span className="mr-1 inline-block h-2 w-2 rounded-full bg-kumo-subtle" />Batang: permutasi null</span>{silhouette?.observed_silhouette != null && <span className="text-kumo-default">Garis tegas: observed {silhouette.observed_silhouette.toFixed(4)}</span>}{silhouette?.random_mean != null && <span className="text-kumo-default">Garis putus-putus: rata-rata null {silhouette.random_mean.toFixed(4)}</span>}</div><div className="mt-4 h-72" role="img" aria-label="Histogram distribusi null permutation Silhouette dengan marker observed dan rata-rata null"><ResponsiveContainer width="100%" height="100%"><BarChart data={nullHistogram} barCategoryGap="0%" margin={{ top: 22, right: 42, bottom: 8, left: 14 }}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="x" type="number" domain={silhouetteBounds.xDomain} tickFormatter={(value) => Number(value).toFixed(3)} height={44} label={{ value: 'Silhouette score', position: 'insideBottom', offset: -3 }} /><YAxis domain={silhouetteBounds.yDomain} width={52} label={{ value: 'Jumlah permutasi', angle: -90, position: 'insideLeft', offset: -2 }} /><Tooltip labelFormatter={(value) => `Silhouette score: ${Number(value).toFixed(4)}`} /><Bar dataKey="count" fill="#9ca3af" name="Null permutations" />{silhouette?.observed_silhouette != null && <ReferenceLine x={silhouette.observed_silhouette} stroke="#0055dc" strokeWidth={2} />}{silhouette?.random_mean != null && <ReferenceLine x={silhouette.random_mean} stroke="#f6821f" strokeDasharray="5 5" />}</BarChart></ResponsiveContainer></div></div>}
      {silhouette?.is_calculable && !nullHistogram.length && <p className="mt-5 rounded-xl bg-kumo-recessed/50 p-4 text-xs leading-5 text-kumo-default">Silhouette menilai pemisahan struktural internal, bukan akurasi atau kebenaran serangan. Artifact ini dibuat sebelum histogram null permutation tersedia; jalankan evaluasi ulang setelah backend diperbarui.</p>}
      {silhouette && !silhouette.is_calculable && <p className="mt-5 rounded-xl bg-kumo-recessed/50 p-4 text-xs leading-5 text-kumo-default">Silhouette tidak dapat dihitung: {silhouette.uncalculable_reason || 'partisi tidak memadai.'}</p>}
    </section>
  );
}

function ChartCard({ title, question, data, xKey = 'delta_t_min', children }: { title: string; question: string; data: Array<Record<string, number | string | null>>; xKey?: string; children: ReactNode }) {
  return <div className="rounded-xl border border-kumo-hairline p-4"><h3 className="text-sm font-semibold text-kumo-strong">{title}</h3><p className="mt-1 text-xs text-kumo-subtle">{question} Sumbu x: {xKey === 'noise_rate' ? 'noise rate (%)' : 'Δt (menit)'}; sumbu y sesuai legenda.</p><div className="mt-4 h-64"><ResponsiveContainer width="100%" height="100%"><LineChart data={data}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey={xKey} /><YAxis /><Tooltip /><Legend />{children}</LineChart></ResponsiveContainer></div></div>;
}
